# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{auto_media_info}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["William Schneider"]
  s.date = %q{2010-02-16}
  s.description = %q{Automatically get media information from the URL.}
  s.email = %q{bananastalktome@gmail.com}
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "README",
     "Rakefile",
     "VERSION.yml",
     "auto_media_info-0.0.1.gem",
     "auto_media_info.gemspec",
     "lib/auto_media_info.rb",
     "lib/auto_media_info/base.rb",
     "lib/auto_media_info/builder.rb",
     "lib/auto_media_info/filter.rb",
     "lib/auto_media_info/filters/youtube.rb"
  ]
  s.homepage = %q{http://github.com/bananastalktome/auto_media_info/}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Automatically get media information from the URL.}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

